### ISSUE TITLE
fluid railcraft

### ISSUE THREAD

**Issue by Aleksey2093** [orangelynx/ic2-extra-fuels#6]
How can I add fuel from railcraft?

https://github.com/Railcraft/Railcraft/blob/mc-1.12.2/src/main/java/mods/railcraft/common/fluids/Fluids.java

**Comment by Aleksey2093** [comment]
fix https://github.com/Aleksey2093/ic2-extra-fuels/commit/da7fb2f834ca3d063bd5f2019785887cb8c42d8a
and use industrialcraft-2:2.8.219-ex112:api

**Comment by orangelynx** [comment]
@Aleksey2093 I do not actively maintain this project anymore, but I'd be happy to merge this, if you create a PR and can confirm this is tested and works.

**Comment by Aleksey2093** [comment]
> @Aleksey2093 I do not actively maintain this project anymore, but I'd be happy to merge this, if you create a PR and can confirm this is tested and works.

ok.
for you https://github.com/orangelynx/ic2-extra-fuels/pull/7

**Comment by orangelynx** [comment]
Thanks alot! Would you like to be developer / maintainer for this project?

**Comment by Aleksey2093** [comment]
> Thanks alot! Would you like to be developer / maintainer for this project?

Don't know yet. I made changes to the project, as I recently assembled an assembly for version 1.12.2 and noticed that it was impossible to use some liquids between modifications. If you suddenly have ideas, I will definitely do PR.
